---
ghq_root: "{{ ansible_user_dir }}/.ghq/github.com"
dotfiles_root: "{{ ghq_root }}/shimx/dotfiles"

git_repositories:
  - { repo: "https://github.com/shimx/dotfiles.git", dest: "{{ ghq_root }}/shimx/dotfiles" }

git_config:
  - { name: "alias.co", value: "checkout", scope: "global" }
  - { name: "alias.st", value: "status", scope: "global" }
  - { name: "alias.ci", value: "commit", scope: "global" }
  - { name: "alias.br", value: "branch", scope: "global" }
  - { name: "alias.sth", value: "stash", scope: "global" }
  - { name: "pager.branch", value: "cat", scope: "global" }

symlinks:
  - { src: "{{ dotfiles_root }}", dest: "{{ ansible_user_dir }}/dotfiles" }
  - { src: "{{ dotfiles_root }}/config/tmux/tmux.conf", dest: "{{ ansible_user_dir }}/.tmux.conf" }
  - { src: "{{ dotfiles_root }}/config/zsh/zshenv", dest: "{{ ansible_user_dir }}/.zshenv" }
  - { src: "{{ dotfiles_root }}/config/zsh/zshrc", dest: "{{ ansible_user_dir }}/.zshrc" }
  - { src: "{{ dotfiles_root }}/config/vim/vimrc", dest: "{{ ansible_user_dir }}/.vimrc" }
