---
- name: Create conf dir
  file:
    dest: "{{ item.dest }}"
    owner: "{{ ansible_user_id }}"
    group: staff
    mode: 0755
    state: directory
  with_items:
    - "{{ directorys }}"

- name: Create conf alias symlink
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  with_items:
    - "{{ symlinks }}"

- name: Install ricty fonts
  shell: |
    cp -f $(brew --cellar ricty)/*/share/fonts/Ricty*.ttf ~/Library/Fonts && fc-cache -vf
  args:
    creates: "{{ ansible_user_dir }}/Library/Fonts/Ricty-Bold.ttf"

- name: Setup OS X defaults
  osx_defaults:
    domain: "{{ item.domain }}"
    key: "{{ item.key }}"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
    state: present
  notify:
    - "{{ item.notify | default(omit) }}"
  with_items:
    - "{{ osx_defaults }}"
